// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetApiEnvironmentsData, GetApiEnvironmentsErrors, GetApiEnvironmentsResponses, GetApiTicketsByTicketIdData, GetApiTicketsByTicketIdErrors, GetApiTicketsByTicketIdResponses, PostApiEnvironmentsData, PostApiEnvironmentsErrors, PostApiEnvironmentsResponses, PutApiWebhooksFailingTestFixStepOutputData, PutApiWebhooksFailingTestFixStepOutputErrors, PutApiWebhooksFailingTestFixStepOutputResponses, PutApiWebhooksFailingTestReproStepOutputData, PutApiWebhooksFailingTestReproStepOutputErrors, PutApiWebhooksFailingTestReproStepOutputResponses, PutApiWebhooksTicketInvestigationStepOutputData, PutApiWebhooksTicketInvestigationStepOutputErrors, PutApiWebhooksTicketInvestigationStepOutputResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

class HeyApiClient {
    protected client: Client;
    
    constructor(args?: {
        client?: Client;
    }) {
        this.client = args?.client ?? client;
    }
}

class HeyApiRegistry<T> {
    private readonly defaultKey = 'default';
    
    private readonly instances: Map<string, T> = new Map();
    
    get(key?: string): T {
        const instance = this.instances.get(key ?? this.defaultKey);
        if (!instance) {
            throw new Error(`No SDK client found. Create one with "new BoboddyClient()" to fix this error.`);
        }
        return instance;
    }
    
    set(value: T, key?: string): void {
        this.instances.set(key ?? this.defaultKey, value);
    }
}

export class Environments extends HeyApiClient {
    /**
     * List environments
     *
     * Returns the environments currently tracked by the service.
     */
    public getApiEnvironments<ThrowOnError extends boolean = false>(options?: Options<GetApiEnvironmentsData, ThrowOnError>) {
        return (options?.client ?? this.client).get<GetApiEnvironmentsResponses, GetApiEnvironmentsErrors, ThrowOnError>({ url: '/api/environments', ...options });
    }
    
    /**
     * Upsert an environment
     *
     * Creates or updates a tracked environment by environment id.
     */
    public postApiEnvironments<ThrowOnError extends boolean = false>(options: Options<PostApiEnvironmentsData, ThrowOnError>) {
        return (options.client ?? this.client).post<PostApiEnvironmentsResponses, PostApiEnvironmentsErrors, ThrowOnError>({
            url: '/api/environments',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * List environments
     *
     * Returns the environments currently tracked by the service.
     */
    public getApiTicketsByTicketId<ThrowOnError extends boolean = false>(options: Options<GetApiTicketsByTicketIdData, ThrowOnError>) {
        return (options.client ?? this.client).get<GetApiTicketsByTicketIdResponses, GetApiTicketsByTicketIdErrors, ThrowOnError>({ url: '/api/tickets/{ticketId}', ...options });
    }
}

export class Webhooks extends HeyApiClient {
    /**
     * Complete a ticket investigation step
     *
     * Processes the ticket-investigation webhook payload and records the step result.
     */
    public putApiWebhooksTicketInvestigationStepOutput<ThrowOnError extends boolean = false>(options: Options<PutApiWebhooksTicketInvestigationStepOutputData, ThrowOnError>) {
        return (options.client ?? this.client).put<PutApiWebhooksTicketInvestigationStepOutputResponses, PutApiWebhooksTicketInvestigationStepOutputErrors, ThrowOnError>({
            url: '/api/webhooks/ticket-investigation-step-output',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Complete a failing test repro step
     *
     * Processes the failing-test-repro webhook payload and records the step result.
     */
    public putApiWebhooksFailingTestReproStepOutput<ThrowOnError extends boolean = false>(options: Options<PutApiWebhooksFailingTestReproStepOutputData, ThrowOnError>) {
        return (options.client ?? this.client).put<PutApiWebhooksFailingTestReproStepOutputResponses, PutApiWebhooksFailingTestReproStepOutputErrors, ThrowOnError>({
            url: '/api/webhooks/failing-test-repro-step-output',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Complete a failing test fix step
     *
     * Processes the failing-test-fix webhook payload and records the step result.
     */
    public putApiWebhooksFailingTestFixStepOutput<ThrowOnError extends boolean = false>(options: Options<PutApiWebhooksFailingTestFixStepOutputData, ThrowOnError>) {
        return (options.client ?? this.client).put<PutApiWebhooksFailingTestFixStepOutputResponses, PutApiWebhooksFailingTestFixStepOutputErrors, ThrowOnError>({
            url: '/api/webhooks/failing-test-fix-step-output',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}

export class BoboddyClient extends HeyApiClient {
    public static readonly __registry = new HeyApiRegistry<BoboddyClient>();
    
    constructor(args?: {
        client?: Client;
        key?: string;
    }) {
        super(args);
        BoboddyClient.__registry.set(this, args?.key);
    }
    
    private _environments?: Environments;
    get environments(): Environments {
        return this._environments ??= new Environments({ client: this.client });
    }
    
    private _webhooks?: Webhooks;
    get webhooks(): Webhooks {
        return this._webhooks ??= new Webhooks({ client: this.client });
    }
}
