// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type GetApiEnvironmentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/environments';
};

export type GetApiEnvironmentsErrors = {
    /**
     * Response for status 404
     */
    404: {
        type: string;
        title: string;
        status: number;
        detail?: string;
        instance?: string;
        code?: string;
        errors?: Array<{
            path: string;
            message: string;
            summary?: string;
        }>;
    };
    /**
     * Response for status 422
     */
    422: {
        type: string;
        title: string;
        status: number;
        detail?: string;
        instance?: string;
        code?: string;
        errors?: Array<{
            path: string;
            message: string;
            summary?: string;
        }>;
    };
    /**
     * Response for status 500
     */
    500: {
        type: string;
        title: string;
        status: number;
        detail?: string;
        instance?: string;
        code?: string;
        errors?: Array<{
            path: string;
            message: string;
            summary?: string;
        }>;
    };
};

export type GetApiEnvironmentsError = GetApiEnvironmentsErrors[keyof GetApiEnvironmentsErrors];

export type GetApiEnvironmentsResponses = {
    /**
     * Response for status 200
     */
    200: Array<{
        environmentId: string;
        area: 'adm' | 'mem' | 'ps';
        number: number;
        region: string;
        databaseHostUrl: string;
        numConsecutiveFailures: number;
        lastChecked: string;
    }>;
};

export type GetApiEnvironmentsResponse = GetApiEnvironmentsResponses[keyof GetApiEnvironmentsResponses];

export type PostApiEnvironmentsData = {
    body: {
        environmentId: string;
        region: string;
        databaseHostUrl: string;
    };
    path?: never;
    query?: never;
    url: '/api/environments';
};

export type PostApiEnvironmentsErrors = {
    /**
     * Response for status 400
     */
    400: {
        type: string;
        title: string;
        status: number;
        detail?: string;
        instance?: string;
        code?: string;
        errors?: Array<{
            path: string;
            message: string;
            summary?: string;
        }>;
    };
    /**
     * Response for status 401
     */
    401: {
        type: string;
        title: string;
        status: number;
        detail?: string;
        instance?: string;
        code?: string;
        errors?: Array<{
            path: string;
            message: string;
            summary?: string;
        }>;
    };
    /**
     * Response for status 500
     */
    500: {
        type: string;
        title: string;
        status: number;
        detail?: string;
        instance?: string;
        code?: string;
        errors?: Array<{
            path: string;
            message: string;
            summary?: string;
        }>;
    };
};

export type PostApiEnvironmentsError = PostApiEnvironmentsErrors[keyof PostApiEnvironmentsErrors];

export type PostApiEnvironmentsResponses = {
    /**
     * Response for status 200
     */
    200: {
        success: boolean;
        environmentId: string;
    };
};

export type PostApiEnvironmentsResponse = PostApiEnvironmentsResponses[keyof PostApiEnvironmentsResponses];

export type GetApiTicketsByTicketIdData = {
    body?: never;
    path: {
        ticketId: string;
    };
    query?: never;
    url: '/api/tickets/{ticketId}';
};

export type GetApiTicketsByTicketIdErrors = {
    /**
     * Response for status 404
     */
    404: {
        type: string;
        title: string;
        status: number;
        detail?: string;
        instance?: string;
        code?: string;
        errors?: Array<{
            path: string;
            message: string;
            summary?: string;
        }>;
    };
    /**
     * Response for status 422
     */
    422: {
        type: string;
        title: string;
        status: number;
        detail?: string;
        instance?: string;
        code?: string;
        errors?: Array<{
            path: string;
            message: string;
            summary?: string;
        }>;
    };
    /**
     * Response for status 500
     */
    500: {
        type: string;
        title: string;
        status: number;
        detail?: string;
        instance?: string;
        code?: string;
        errors?: Array<{
            path: string;
            message: string;
            summary?: string;
        }>;
    };
};

export type GetApiTicketsByTicketIdError = GetApiTicketsByTicketIdErrors[keyof GetApiTicketsByTicketIdErrors];

export type GetApiTicketsByTicketIdResponses = {
    /**
     * Response for status 200
     */
    200: {
        ticket: {
            id: string;
            ticketNumber: string;
            title: string;
            slackThread: string | unknown;
            status: 'needs_more_information' | 'needs_triage' | 'triaged_backlog' | 'in_progress' | 'ops_resolution_needed' | 'done';
            description: string;
            companyNames: Array<string>;
            employeeEmails: Array<string>;
            priority: 'lowest' | 'low' | 'medium' | 'high' | 'highest';
            ticketType: 'bug' | 'manual support' | 'enhancement' | 'report request';
            dueDate: string | unknown;
            reporter: string;
            reporterAccountId?: string | unknown;
            assignee: string | unknown;
            jiraCreatedAt: string | unknown;
            jiraUpdatedAt: string | unknown;
            pipelineSteps?: Array<{
                id: unknown & unknown;
                pipelineId: string | unknown;
                ticketId: string;
                stepName: string;
                status: 'not_started' | 'queued' | 'running' | 'waiting_for_user_feedback' | 'succeeded' | 'failed' | 'skipped' | 'failed_timeout';
                startedAt: string;
                endedAt: string | unknown;
                createdAt: string;
                updatedAt: string;
                failureReason: string | unknown;
                result: {
                    executionId: unknown & unknown;
                    stepName: string;
                    stepsToReproduceScore: number;
                    expectedBehaviorScore: number;
                    observedBehaviorScore: number;
                    reasoning: string;
                    rawResponse: string;
                    createdAt?: string;
                    updatedAt?: string;
                } | {
                    whatHappened: string;
                    datadogQueryTerms: Array<string>;
                    datadogTimeRange: string | unknown;
                    keyIdentifiers: Array<string>;
                    exactEventTimes: Array<string>;
                    codeUnitsInvolved: Array<{
                        kind: 'api_route' | 'frontend_route' | 'method' | 'class' | 'frontend_component' | 'function' | 'module' | 'unknown';
                        name: string;
                        filePath: string | unknown;
                        symbol: string | unknown;
                        relevance: string;
                        evidence: Array<string>;
                        notes: Array<string>;
                    }>;
                    databaseFindings: Array<{
                        entityType: string;
                        relationToTicket: string;
                        identifiers: Array<string>;
                        records: Array<{
                            [key: string]: unknown;
                        }>;
                        comparisonNotes: Array<string>;
                        notes: Array<string>;
                    }>;
                    logFindings: Array<{
                        source: 'frontend_route' | 'application_log' | 'datadog_log' | 'trace' | 'unknown';
                        routeOrCodePath: string | unknown;
                        queryOrFilter: string | unknown;
                        timestamp: string | unknown;
                        message: string;
                        identifiers: Array<string>;
                        evidence: Array<string>;
                        notes: Array<string>;
                    }>;
                    datadogSessionFindings: Array<{
                        userIdentifier: string;
                        sessionId: string | unknown;
                        timeWindow: string;
                        events: Array<{
                            timestamp: string | unknown;
                            type: string;
                            description: string;
                            route: string | unknown;
                            metadata: {
                                [key: string]: unknown;
                            };
                        }>;
                        notes: Array<string>;
                    }>;
                    investigationGaps: Array<string>;
                    recommendedNextQueries: Array<string>;
                    executionId: unknown & unknown;
                    stepName: string;
                    summaryOfInvestigation: string;
                    investigationReport: string;
                    confidenceLevel: number | unknown;
                    agentStatus: 'complete' | 'error' | 'abort' | 'timeout' | 'user_exit';
                    agentBranch: string;
                    operationOutcome: 'findings_recorded' | 'inconclusive' | 'agent_error' | 'cancelled';
                    rawResultJson: {
                        [key: string]: unknown;
                    };
                    createdAt?: string;
                    updatedAt?: string;
                } | {
                    executionId: unknown & unknown;
                    stepName: string;
                    proposed: Array<{
                        candidateTicketId: string;
                        score: number;
                    }>;
                    dismissed: Array<{
                        candidateTicketId: string;
                        score: number;
                    }>;
                    promoted: Array<{
                        candidateTicketId: string;
                        score: number;
                    }>;
                    createdAt?: string;
                    updatedAt?: string;
                } | {
                    executionId: unknown & unknown;
                    stepName: string;
                    agentStatus: 'complete' | 'error' | 'abort' | 'timeout' | 'user_exit';
                    agentBranch: string;
                    traceArtifactPath: string | unknown;
                    outcome: 'reproduced' | 'not_reproducible' | 'needs_user_feedback' | 'agent_error' | 'cancelled' | 'timeout';
                    summaryOfFindings: string;
                    confidenceLevel: number | unknown;
                    feedbackRequest: {
                        requestId: string;
                        reason: string;
                        questions: Array<string>;
                        assumptions: Array<string>;
                    } | unknown;
                    failureReason: string | unknown;
                    timeoutMs: number | unknown;
                    rawResultJson: {
                        [key: string]: unknown;
                    } | unknown;
                    createdAt?: string;
                    updatedAt?: string;
                } | {
                    executionId: unknown & unknown;
                    stepName: string;
                    githubAgentRunId: string | unknown;
                    githubMergeStatus: 'draft' | 'open' | 'closed' | 'merged';
                    devBranch: string | unknown;
                    baseBranch: string | unknown;
                    agentStatus: 'complete' | 'error' | 'abort' | 'timeout' | 'user_exit' | unknown;
                    agentBranch: string | unknown;
                    failingTestPaths: Array<string> | unknown;
                    failingTestCommitSha: string | unknown;
                    outcome: 'reproduced' | 'not_reproducible' | 'needs_user_feedback' | 'agent_error' | 'cancelled' | unknown;
                    summaryOfFindings: string | unknown;
                    confidenceLevel: number | unknown;
                    feedbackRequest: {
                        requestId: string;
                        reason: string;
                        questions: Array<string>;
                        assumptions: Array<string>;
                    } | unknown;
                    failureReason: string | unknown;
                    rawResultJson: {
                        [key: string]: unknown;
                    } | unknown;
                    createdAt?: string;
                    updatedAt?: string;
                } | {
                    executionId: unknown & unknown;
                    stepName: string;
                    githubAgentRunId: string | unknown;
                    githubMergeStatus: 'draft' | 'open' | 'closed' | 'merged';
                    devBranch: string | unknown;
                    baseBranch: string | unknown;
                    agentStatus: 'complete' | 'error' | 'abort' | 'timeout' | 'user_exit' | unknown;
                    agentBranch: string | unknown;
                    agentSummary: string | unknown;
                    fixedTestPath: string | unknown;
                    failingTestCommitSha?: string | unknown;
                    fixOperationOutcome: 'fixed' | 'not_fixed' | 'agent_error' | 'cancelled' | unknown;
                    summaryOfFix: string | unknown;
                    fixConfidenceLevel: number | unknown;
                    failureReason: string | unknown;
                    rawResultJson: {
                        [key: string]: unknown;
                    } | unknown;
                    createdAt?: string;
                    updatedAt?: string;
                } | unknown;
            }>;
            defaultGitEnvironmentId?: number;
            defaultGitEnvironment?: {
                id: number;
                baseEnvironmentId: string;
                baseBranch: string;
                devBranch: string;
            };
            createdAt: string;
            updatedAt: string;
        };
        pipeline: {
            stepExecutions: Array<{
                id: unknown & unknown;
                pipelineId: string | unknown;
                ticketId: string;
                stepName: string;
                status: 'not_started' | 'queued' | 'running' | 'waiting_for_user_feedback' | 'succeeded' | 'failed' | 'skipped' | 'failed_timeout';
                startedAt: string;
                endedAt: string | unknown;
                createdAt: string;
                updatedAt: string;
                failureReason: string | unknown;
                result: {
                    executionId: unknown & unknown;
                    stepName: string;
                    stepsToReproduceScore: number;
                    expectedBehaviorScore: number;
                    observedBehaviorScore: number;
                    reasoning: string;
                    rawResponse: string;
                    createdAt?: string;
                    updatedAt?: string;
                } | {
                    whatHappened: string;
                    datadogQueryTerms: Array<string>;
                    datadogTimeRange: string | unknown;
                    keyIdentifiers: Array<string>;
                    exactEventTimes: Array<string>;
                    codeUnitsInvolved: Array<{
                        kind: 'api_route' | 'frontend_route' | 'method' | 'class' | 'frontend_component' | 'function' | 'module' | 'unknown';
                        name: string;
                        filePath: string | unknown;
                        symbol: string | unknown;
                        relevance: string;
                        evidence: Array<string>;
                        notes: Array<string>;
                    }>;
                    databaseFindings: Array<{
                        entityType: string;
                        relationToTicket: string;
                        identifiers: Array<string>;
                        records: Array<{
                            [key: string]: unknown;
                        }>;
                        comparisonNotes: Array<string>;
                        notes: Array<string>;
                    }>;
                    logFindings: Array<{
                        source: 'frontend_route' | 'application_log' | 'datadog_log' | 'trace' | 'unknown';
                        routeOrCodePath: string | unknown;
                        queryOrFilter: string | unknown;
                        timestamp: string | unknown;
                        message: string;
                        identifiers: Array<string>;
                        evidence: Array<string>;
                        notes: Array<string>;
                    }>;
                    datadogSessionFindings: Array<{
                        userIdentifier: string;
                        sessionId: string | unknown;
                        timeWindow: string;
                        events: Array<{
                            timestamp: string | unknown;
                            type: string;
                            description: string;
                            route: string | unknown;
                            metadata: {
                                [key: string]: unknown;
                            };
                        }>;
                        notes: Array<string>;
                    }>;
                    investigationGaps: Array<string>;
                    recommendedNextQueries: Array<string>;
                    executionId: unknown & unknown;
                    stepName: string;
                    summaryOfInvestigation: string;
                    investigationReport: string;
                    confidenceLevel: number | unknown;
                    agentStatus: 'complete' | 'error' | 'abort' | 'timeout' | 'user_exit';
                    agentBranch: string;
                    operationOutcome: 'findings_recorded' | 'inconclusive' | 'agent_error' | 'cancelled';
                    rawResultJson: {
                        [key: string]: unknown;
                    };
                    createdAt?: string;
                    updatedAt?: string;
                } | {
                    executionId: unknown & unknown;
                    stepName: string;
                    proposed: Array<{
                        candidateTicketId: string;
                        score: number;
                    }>;
                    dismissed: Array<{
                        candidateTicketId: string;
                        score: number;
                    }>;
                    promoted: Array<{
                        candidateTicketId: string;
                        score: number;
                    }>;
                    createdAt?: string;
                    updatedAt?: string;
                } | {
                    executionId: unknown & unknown;
                    stepName: string;
                    agentStatus: 'complete' | 'error' | 'abort' | 'timeout' | 'user_exit';
                    agentBranch: string;
                    traceArtifactPath: string | unknown;
                    outcome: 'reproduced' | 'not_reproducible' | 'needs_user_feedback' | 'agent_error' | 'cancelled' | 'timeout';
                    summaryOfFindings: string;
                    confidenceLevel: number | unknown;
                    feedbackRequest: {
                        requestId: string;
                        reason: string;
                        questions: Array<string>;
                        assumptions: Array<string>;
                    } | unknown;
                    failureReason: string | unknown;
                    timeoutMs: number | unknown;
                    rawResultJson: {
                        [key: string]: unknown;
                    } | unknown;
                    createdAt?: string;
                    updatedAt?: string;
                } | {
                    executionId: unknown & unknown;
                    stepName: string;
                    githubAgentRunId: string | unknown;
                    githubMergeStatus: 'draft' | 'open' | 'closed' | 'merged';
                    devBranch: string | unknown;
                    baseBranch: string | unknown;
                    agentStatus: 'complete' | 'error' | 'abort' | 'timeout' | 'user_exit' | unknown;
                    agentBranch: string | unknown;
                    failingTestPaths: Array<string> | unknown;
                    failingTestCommitSha: string | unknown;
                    outcome: 'reproduced' | 'not_reproducible' | 'needs_user_feedback' | 'agent_error' | 'cancelled' | unknown;
                    summaryOfFindings: string | unknown;
                    confidenceLevel: number | unknown;
                    feedbackRequest: {
                        requestId: string;
                        reason: string;
                        questions: Array<string>;
                        assumptions: Array<string>;
                    } | unknown;
                    failureReason: string | unknown;
                    rawResultJson: {
                        [key: string]: unknown;
                    } | unknown;
                    createdAt?: string;
                    updatedAt?: string;
                } | {
                    executionId: unknown & unknown;
                    stepName: string;
                    githubAgentRunId: string | unknown;
                    githubMergeStatus: 'draft' | 'open' | 'closed' | 'merged';
                    devBranch: string | unknown;
                    baseBranch: string | unknown;
                    agentStatus: 'complete' | 'error' | 'abort' | 'timeout' | 'user_exit' | unknown;
                    agentBranch: string | unknown;
                    agentSummary: string | unknown;
                    fixedTestPath: string | unknown;
                    failingTestCommitSha?: string | unknown;
                    fixOperationOutcome: 'fixed' | 'not_fixed' | 'agent_error' | 'cancelled' | unknown;
                    summaryOfFix: string | unknown;
                    fixConfidenceLevel: number | unknown;
                    failureReason: string | unknown;
                    rawResultJson: {
                        [key: string]: unknown;
                    } | unknown;
                    createdAt?: string;
                    updatedAt?: string;
                } | unknown;
            }>;
        };
    };
};

export type GetApiTicketsByTicketIdResponse = GetApiTicketsByTicketIdResponses[keyof GetApiTicketsByTicketIdResponses];

export type PutApiWebhooksTicketInvestigationStepOutputData = {
    body: {
        whatHappened: string;
        datadogQueryTerms: Array<string>;
        datadogTimeRange: string | unknown;
        keyIdentifiers: Array<string>;
        exactEventTimes: Array<string>;
        codeUnitsInvolved: Array<{
            kind: 'api_route' | 'frontend_route' | 'method' | 'class' | 'frontend_component' | 'function' | 'module' | 'unknown';
            name: string;
            filePath: string | unknown;
            symbol: string | unknown;
            relevance: string;
            evidence: Array<string>;
            notes: Array<string>;
        }>;
        databaseFindings: Array<{
            entityType: string;
            relationToTicket: string;
            identifiers: Array<string>;
            records: Array<{
                [key: string]: unknown;
            }>;
            comparisonNotes: Array<string>;
            notes: Array<string>;
        }>;
        logFindings: Array<{
            source: 'frontend_route' | 'application_log' | 'datadog_log' | 'trace' | 'unknown';
            routeOrCodePath: string | unknown;
            queryOrFilter: string | unknown;
            timestamp: string | unknown;
            message: string;
            identifiers: Array<string>;
            evidence: Array<string>;
            notes: Array<string>;
        }>;
        datadogSessionFindings: Array<{
            userIdentifier: string;
            sessionId: string | unknown;
            timeWindow: string;
            events: Array<{
                timestamp: string | unknown;
                type: string;
                description: string;
                route: string | unknown;
                metadata: {
                    [key: string]: unknown;
                };
            }>;
            notes: Array<string>;
        }>;
        investigationGaps: Array<string>;
        recommendedNextQueries: Array<string>;
        operationOutcome: 'findings_recorded' | 'inconclusive' | 'agent_error' | 'cancelled';
        summaryOfInvestigation: string;
        investigationReport: string;
        confidenceLevel: number | unknown;
        rawResultJson: {
            [key: string]: unknown;
        };
    };
    path?: never;
    query: {
        agentStatus: 'complete' | 'error' | 'abort' | 'timeout' | 'user_exit';
        agentBranch: string;
        stepExecutionId: string;
    };
    url: '/api/webhooks/ticket-investigation-step-output';
};

export type PutApiWebhooksTicketInvestigationStepOutputErrors = {
    /**
     * Response for status 400
     */
    400: {
        type: string;
        title: string;
        status: number;
        detail?: string;
        instance?: string;
        code?: string;
        errors?: Array<{
            path: string;
            message: string;
            summary?: string;
        }>;
    };
    /**
     * Response for status 404
     */
    404: {
        type: string;
        title: string;
        status: number;
        detail?: string;
        instance?: string;
        code?: string;
        errors?: Array<{
            path: string;
            message: string;
            summary?: string;
        }>;
    };
    /**
     * Response for status 409
     */
    409: {
        type: string;
        title: string;
        status: number;
        detail?: string;
        instance?: string;
        code?: string;
        errors?: Array<{
            path: string;
            message: string;
            summary?: string;
        }>;
    };
    /**
     * Response for status 500
     */
    500: {
        type: string;
        title: string;
        status: number;
        detail?: string;
        instance?: string;
        code?: string;
        errors?: Array<{
            path: string;
            message: string;
            summary?: string;
        }>;
    };
};

export type PutApiWebhooksTicketInvestigationStepOutputError = PutApiWebhooksTicketInvestigationStepOutputErrors[keyof PutApiWebhooksTicketInvestigationStepOutputErrors];

export type PutApiWebhooksTicketInvestigationStepOutputResponses = {
    /**
     * Response for status 200
     */
    200: {
        ok: boolean;
        data: {
            stepExecution: {
                id: unknown & unknown;
                pipelineId: string | unknown;
                ticketId: string;
                stepName: string;
                status: 'not_started' | 'queued' | 'running' | 'waiting_for_user_feedback' | 'succeeded' | 'failed' | 'skipped' | 'failed_timeout';
                startedAt: string;
                endedAt: string | unknown;
                createdAt: string;
                updatedAt: string;
                failureReason: string | unknown;
                result: {
                    executionId: unknown & unknown;
                    stepName: string;
                    stepsToReproduceScore: number;
                    expectedBehaviorScore: number;
                    observedBehaviorScore: number;
                    reasoning: string;
                    rawResponse: string;
                    createdAt?: string;
                    updatedAt?: string;
                } | {
                    whatHappened: string;
                    datadogQueryTerms: Array<string>;
                    datadogTimeRange: string | unknown;
                    keyIdentifiers: Array<string>;
                    exactEventTimes: Array<string>;
                    codeUnitsInvolved: Array<{
                        kind: 'api_route' | 'frontend_route' | 'method' | 'class' | 'frontend_component' | 'function' | 'module' | 'unknown';
                        name: string;
                        filePath: string | unknown;
                        symbol: string | unknown;
                        relevance: string;
                        evidence: Array<string>;
                        notes: Array<string>;
                    }>;
                    databaseFindings: Array<{
                        entityType: string;
                        relationToTicket: string;
                        identifiers: Array<string>;
                        records: Array<{
                            [key: string]: unknown;
                        }>;
                        comparisonNotes: Array<string>;
                        notes: Array<string>;
                    }>;
                    logFindings: Array<{
                        source: 'frontend_route' | 'application_log' | 'datadog_log' | 'trace' | 'unknown';
                        routeOrCodePath: string | unknown;
                        queryOrFilter: string | unknown;
                        timestamp: string | unknown;
                        message: string;
                        identifiers: Array<string>;
                        evidence: Array<string>;
                        notes: Array<string>;
                    }>;
                    datadogSessionFindings: Array<{
                        userIdentifier: string;
                        sessionId: string | unknown;
                        timeWindow: string;
                        events: Array<{
                            timestamp: string | unknown;
                            type: string;
                            description: string;
                            route: string | unknown;
                            metadata: {
                                [key: string]: unknown;
                            };
                        }>;
                        notes: Array<string>;
                    }>;
                    investigationGaps: Array<string>;
                    recommendedNextQueries: Array<string>;
                    executionId: unknown & unknown;
                    stepName: string;
                    summaryOfInvestigation: string;
                    investigationReport: string;
                    confidenceLevel: number | unknown;
                    agentStatus: 'complete' | 'error' | 'abort' | 'timeout' | 'user_exit';
                    agentBranch: string;
                    operationOutcome: 'findings_recorded' | 'inconclusive' | 'agent_error' | 'cancelled';
                    rawResultJson: {
                        [key: string]: unknown;
                    };
                    createdAt?: string;
                    updatedAt?: string;
                } | {
                    executionId: unknown & unknown;
                    stepName: string;
                    proposed: Array<{
                        candidateTicketId: string;
                        score: number;
                    }>;
                    dismissed: Array<{
                        candidateTicketId: string;
                        score: number;
                    }>;
                    promoted: Array<{
                        candidateTicketId: string;
                        score: number;
                    }>;
                    createdAt?: string;
                    updatedAt?: string;
                } | {
                    executionId: unknown & unknown;
                    stepName: string;
                    agentStatus: 'complete' | 'error' | 'abort' | 'timeout' | 'user_exit';
                    agentBranch: string;
                    traceArtifactPath: string | unknown;
                    outcome: 'reproduced' | 'not_reproducible' | 'needs_user_feedback' | 'agent_error' | 'cancelled' | 'timeout';
                    summaryOfFindings: string;
                    confidenceLevel: number | unknown;
                    feedbackRequest: {
                        requestId: string;
                        reason: string;
                        questions: Array<string>;
                        assumptions: Array<string>;
                    } | unknown;
                    failureReason: string | unknown;
                    timeoutMs: number | unknown;
                    rawResultJson: {
                        [key: string]: unknown;
                    } | unknown;
                    createdAt?: string;
                    updatedAt?: string;
                } | {
                    executionId: unknown & unknown;
                    stepName: string;
                    githubAgentRunId: string | unknown;
                    githubMergeStatus: 'draft' | 'open' | 'closed' | 'merged';
                    devBranch: string | unknown;
                    baseBranch: string | unknown;
                    agentStatus: 'complete' | 'error' | 'abort' | 'timeout' | 'user_exit' | unknown;
                    agentBranch: string | unknown;
                    failingTestPaths: Array<string> | unknown;
                    failingTestCommitSha: string | unknown;
                    outcome: 'reproduced' | 'not_reproducible' | 'needs_user_feedback' | 'agent_error' | 'cancelled' | unknown;
                    summaryOfFindings: string | unknown;
                    confidenceLevel: number | unknown;
                    feedbackRequest: {
                        requestId: string;
                        reason: string;
                        questions: Array<string>;
                        assumptions: Array<string>;
                    } | unknown;
                    failureReason: string | unknown;
                    rawResultJson: {
                        [key: string]: unknown;
                    } | unknown;
                    createdAt?: string;
                    updatedAt?: string;
                } | {
                    executionId: unknown & unknown;
                    stepName: string;
                    githubAgentRunId: string | unknown;
                    githubMergeStatus: 'draft' | 'open' | 'closed' | 'merged';
                    devBranch: string | unknown;
                    baseBranch: string | unknown;
                    agentStatus: 'complete' | 'error' | 'abort' | 'timeout' | 'user_exit' | unknown;
                    agentBranch: string | unknown;
                    agentSummary: string | unknown;
                    fixedTestPath: string | unknown;
                    failingTestCommitSha?: string | unknown;
                    fixOperationOutcome: 'fixed' | 'not_fixed' | 'agent_error' | 'cancelled' | unknown;
                    summaryOfFix: string | unknown;
                    fixConfidenceLevel: number | unknown;
                    failureReason: string | unknown;
                    rawResultJson: {
                        [key: string]: unknown;
                    } | unknown;
                    createdAt?: string;
                    updatedAt?: string;
                } | unknown;
            };
        };
    };
};

export type PutApiWebhooksTicketInvestigationStepOutputResponse = PutApiWebhooksTicketInvestigationStepOutputResponses[keyof PutApiWebhooksTicketInvestigationStepOutputResponses];

export type PutApiWebhooksFailingTestReproStepOutputData = {
    body: {
        summaryOfFindings: string;
        reproduceOperationOutcome: string;
        confidenceLevel: number;
        failingTestPaths: Array<string>;
        feedbackRequest: unknown;
    } | {
        summaryOfFindings: string;
        reproduceOperationOutcome: string;
        confidenceLevel: number;
        failingTestPaths: unknown;
        feedbackRequest: unknown;
    } | {
        summaryOfFindings: string;
        reproduceOperationOutcome: string;
        confidenceLevel: unknown;
        failingTestPaths: unknown;
        feedbackRequest: {
            requestId: string;
            reason: string;
            questions: Array<string>;
            assumptions: Array<string>;
        };
    } | {
        summaryOfFindings: string;
        reproduceOperationOutcome: string;
        confidenceLevel: unknown;
        failingTestPaths: unknown;
        feedbackRequest: unknown;
    } | {
        summaryOfFindings: string;
        reproduceOperationOutcome: string;
        confidenceLevel: unknown;
        failingTestPaths: unknown;
        feedbackRequest: unknown;
    };
    path?: never;
    query: {
        agentStatus: 'complete' | 'error' | 'abort' | 'timeout' | 'user_exit';
        agentBranch: string;
        stepExecutionId: string;
    };
    url: '/api/webhooks/failing-test-repro-step-output';
};

export type PutApiWebhooksFailingTestReproStepOutputErrors = {
    /**
     * Response for status 400
     */
    400: {
        type: string;
        title: string;
        status: number;
        detail?: string;
        instance?: string;
        code?: string;
        errors?: Array<{
            path: string;
            message: string;
            summary?: string;
        }>;
    };
    /**
     * Response for status 404
     */
    404: {
        type: string;
        title: string;
        status: number;
        detail?: string;
        instance?: string;
        code?: string;
        errors?: Array<{
            path: string;
            message: string;
            summary?: string;
        }>;
    };
    /**
     * Response for status 409
     */
    409: {
        type: string;
        title: string;
        status: number;
        detail?: string;
        instance?: string;
        code?: string;
        errors?: Array<{
            path: string;
            message: string;
            summary?: string;
        }>;
    };
    /**
     * Response for status 500
     */
    500: {
        type: string;
        title: string;
        status: number;
        detail?: string;
        instance?: string;
        code?: string;
        errors?: Array<{
            path: string;
            message: string;
            summary?: string;
        }>;
    };
};

export type PutApiWebhooksFailingTestReproStepOutputError = PutApiWebhooksFailingTestReproStepOutputErrors[keyof PutApiWebhooksFailingTestReproStepOutputErrors];

export type PutApiWebhooksFailingTestReproStepOutputResponses = {
    /**
     * Response for status 200
     */
    200: {
        ok: boolean;
        data: {
            stepExecution: {
                id: unknown & unknown;
                pipelineId: string | unknown;
                ticketId: string;
                stepName: string;
                status: 'not_started' | 'queued' | 'running' | 'waiting_for_user_feedback' | 'succeeded' | 'failed' | 'skipped' | 'failed_timeout';
                startedAt: string;
                endedAt: string | unknown;
                createdAt: string;
                updatedAt: string;
                failureReason: string | unknown;
                result: {
                    executionId: unknown & unknown;
                    stepName: string;
                    stepsToReproduceScore: number;
                    expectedBehaviorScore: number;
                    observedBehaviorScore: number;
                    reasoning: string;
                    rawResponse: string;
                    createdAt?: string;
                    updatedAt?: string;
                } | {
                    whatHappened: string;
                    datadogQueryTerms: Array<string>;
                    datadogTimeRange: string | unknown;
                    keyIdentifiers: Array<string>;
                    exactEventTimes: Array<string>;
                    codeUnitsInvolved: Array<{
                        kind: 'api_route' | 'frontend_route' | 'method' | 'class' | 'frontend_component' | 'function' | 'module' | 'unknown';
                        name: string;
                        filePath: string | unknown;
                        symbol: string | unknown;
                        relevance: string;
                        evidence: Array<string>;
                        notes: Array<string>;
                    }>;
                    databaseFindings: Array<{
                        entityType: string;
                        relationToTicket: string;
                        identifiers: Array<string>;
                        records: Array<{
                            [key: string]: unknown;
                        }>;
                        comparisonNotes: Array<string>;
                        notes: Array<string>;
                    }>;
                    logFindings: Array<{
                        source: 'frontend_route' | 'application_log' | 'datadog_log' | 'trace' | 'unknown';
                        routeOrCodePath: string | unknown;
                        queryOrFilter: string | unknown;
                        timestamp: string | unknown;
                        message: string;
                        identifiers: Array<string>;
                        evidence: Array<string>;
                        notes: Array<string>;
                    }>;
                    datadogSessionFindings: Array<{
                        userIdentifier: string;
                        sessionId: string | unknown;
                        timeWindow: string;
                        events: Array<{
                            timestamp: string | unknown;
                            type: string;
                            description: string;
                            route: string | unknown;
                            metadata: {
                                [key: string]: unknown;
                            };
                        }>;
                        notes: Array<string>;
                    }>;
                    investigationGaps: Array<string>;
                    recommendedNextQueries: Array<string>;
                    executionId: unknown & unknown;
                    stepName: string;
                    summaryOfInvestigation: string;
                    investigationReport: string;
                    confidenceLevel: number | unknown;
                    agentStatus: 'complete' | 'error' | 'abort' | 'timeout' | 'user_exit';
                    agentBranch: string;
                    operationOutcome: 'findings_recorded' | 'inconclusive' | 'agent_error' | 'cancelled';
                    rawResultJson: {
                        [key: string]: unknown;
                    };
                    createdAt?: string;
                    updatedAt?: string;
                } | {
                    executionId: unknown & unknown;
                    stepName: string;
                    proposed: Array<{
                        candidateTicketId: string;
                        score: number;
                    }>;
                    dismissed: Array<{
                        candidateTicketId: string;
                        score: number;
                    }>;
                    promoted: Array<{
                        candidateTicketId: string;
                        score: number;
                    }>;
                    createdAt?: string;
                    updatedAt?: string;
                } | {
                    executionId: unknown & unknown;
                    stepName: string;
                    agentStatus: 'complete' | 'error' | 'abort' | 'timeout' | 'user_exit';
                    agentBranch: string;
                    traceArtifactPath: string | unknown;
                    outcome: 'reproduced' | 'not_reproducible' | 'needs_user_feedback' | 'agent_error' | 'cancelled' | 'timeout';
                    summaryOfFindings: string;
                    confidenceLevel: number | unknown;
                    feedbackRequest: {
                        requestId: string;
                        reason: string;
                        questions: Array<string>;
                        assumptions: Array<string>;
                    } | unknown;
                    failureReason: string | unknown;
                    timeoutMs: number | unknown;
                    rawResultJson: {
                        [key: string]: unknown;
                    } | unknown;
                    createdAt?: string;
                    updatedAt?: string;
                } | {
                    executionId: unknown & unknown;
                    stepName: string;
                    githubAgentRunId: string | unknown;
                    githubMergeStatus: 'draft' | 'open' | 'closed' | 'merged';
                    devBranch: string | unknown;
                    baseBranch: string | unknown;
                    agentStatus: 'complete' | 'error' | 'abort' | 'timeout' | 'user_exit' | unknown;
                    agentBranch: string | unknown;
                    failingTestPaths: Array<string> | unknown;
                    failingTestCommitSha: string | unknown;
                    outcome: 'reproduced' | 'not_reproducible' | 'needs_user_feedback' | 'agent_error' | 'cancelled' | unknown;
                    summaryOfFindings: string | unknown;
                    confidenceLevel: number | unknown;
                    feedbackRequest: {
                        requestId: string;
                        reason: string;
                        questions: Array<string>;
                        assumptions: Array<string>;
                    } | unknown;
                    failureReason: string | unknown;
                    rawResultJson: {
                        [key: string]: unknown;
                    } | unknown;
                    createdAt?: string;
                    updatedAt?: string;
                } | {
                    executionId: unknown & unknown;
                    stepName: string;
                    githubAgentRunId: string | unknown;
                    githubMergeStatus: 'draft' | 'open' | 'closed' | 'merged';
                    devBranch: string | unknown;
                    baseBranch: string | unknown;
                    agentStatus: 'complete' | 'error' | 'abort' | 'timeout' | 'user_exit' | unknown;
                    agentBranch: string | unknown;
                    agentSummary: string | unknown;
                    fixedTestPath: string | unknown;
                    failingTestCommitSha?: string | unknown;
                    fixOperationOutcome: 'fixed' | 'not_fixed' | 'agent_error' | 'cancelled' | unknown;
                    summaryOfFix: string | unknown;
                    fixConfidenceLevel: number | unknown;
                    failureReason: string | unknown;
                    rawResultJson: {
                        [key: string]: unknown;
                    } | unknown;
                    createdAt?: string;
                    updatedAt?: string;
                } | unknown;
            };
        };
    };
};

export type PutApiWebhooksFailingTestReproStepOutputResponse = PutApiWebhooksFailingTestReproStepOutputResponses[keyof PutApiWebhooksFailingTestReproStepOutputResponses];

export type PutApiWebhooksFailingTestFixStepOutputData = {
    body: {
        fixOperationOutcome: 'fixed' | 'not_fixed' | 'agent_error' | 'cancelled';
        summaryOfFix: string;
        fixConfidenceLevel: number | unknown;
        fixedTestPath: string | unknown;
    };
    path?: never;
    query: {
        agentStatus: 'complete' | 'error' | 'abort' | 'timeout' | 'user_exit';
        agentBranch: string;
        stepExecutionId: string;
    };
    url: '/api/webhooks/failing-test-fix-step-output';
};

export type PutApiWebhooksFailingTestFixStepOutputErrors = {
    /**
     * Response for status 400
     */
    400: {
        type: string;
        title: string;
        status: number;
        detail?: string;
        instance?: string;
        code?: string;
        errors?: Array<{
            path: string;
            message: string;
            summary?: string;
        }>;
    };
    /**
     * Response for status 404
     */
    404: {
        type: string;
        title: string;
        status: number;
        detail?: string;
        instance?: string;
        code?: string;
        errors?: Array<{
            path: string;
            message: string;
            summary?: string;
        }>;
    };
    /**
     * Response for status 409
     */
    409: {
        type: string;
        title: string;
        status: number;
        detail?: string;
        instance?: string;
        code?: string;
        errors?: Array<{
            path: string;
            message: string;
            summary?: string;
        }>;
    };
    /**
     * Response for status 500
     */
    500: {
        type: string;
        title: string;
        status: number;
        detail?: string;
        instance?: string;
        code?: string;
        errors?: Array<{
            path: string;
            message: string;
            summary?: string;
        }>;
    };
};

export type PutApiWebhooksFailingTestFixStepOutputError = PutApiWebhooksFailingTestFixStepOutputErrors[keyof PutApiWebhooksFailingTestFixStepOutputErrors];

export type PutApiWebhooksFailingTestFixStepOutputResponses = {
    /**
     * Response for status 200
     */
    200: {
        ok: boolean;
        data: {
            stepExecution: {
                id: unknown & unknown;
                pipelineId: string | unknown;
                ticketId: string;
                stepName: string;
                status: 'not_started' | 'queued' | 'running' | 'waiting_for_user_feedback' | 'succeeded' | 'failed' | 'skipped' | 'failed_timeout';
                startedAt: string;
                endedAt: string | unknown;
                createdAt: string;
                updatedAt: string;
                failureReason: string | unknown;
                result: {
                    executionId: unknown & unknown;
                    stepName: string;
                    stepsToReproduceScore: number;
                    expectedBehaviorScore: number;
                    observedBehaviorScore: number;
                    reasoning: string;
                    rawResponse: string;
                    createdAt?: string;
                    updatedAt?: string;
                } | {
                    whatHappened: string;
                    datadogQueryTerms: Array<string>;
                    datadogTimeRange: string | unknown;
                    keyIdentifiers: Array<string>;
                    exactEventTimes: Array<string>;
                    codeUnitsInvolved: Array<{
                        kind: 'api_route' | 'frontend_route' | 'method' | 'class' | 'frontend_component' | 'function' | 'module' | 'unknown';
                        name: string;
                        filePath: string | unknown;
                        symbol: string | unknown;
                        relevance: string;
                        evidence: Array<string>;
                        notes: Array<string>;
                    }>;
                    databaseFindings: Array<{
                        entityType: string;
                        relationToTicket: string;
                        identifiers: Array<string>;
                        records: Array<{
                            [key: string]: unknown;
                        }>;
                        comparisonNotes: Array<string>;
                        notes: Array<string>;
                    }>;
                    logFindings: Array<{
                        source: 'frontend_route' | 'application_log' | 'datadog_log' | 'trace' | 'unknown';
                        routeOrCodePath: string | unknown;
                        queryOrFilter: string | unknown;
                        timestamp: string | unknown;
                        message: string;
                        identifiers: Array<string>;
                        evidence: Array<string>;
                        notes: Array<string>;
                    }>;
                    datadogSessionFindings: Array<{
                        userIdentifier: string;
                        sessionId: string | unknown;
                        timeWindow: string;
                        events: Array<{
                            timestamp: string | unknown;
                            type: string;
                            description: string;
                            route: string | unknown;
                            metadata: {
                                [key: string]: unknown;
                            };
                        }>;
                        notes: Array<string>;
                    }>;
                    investigationGaps: Array<string>;
                    recommendedNextQueries: Array<string>;
                    executionId: unknown & unknown;
                    stepName: string;
                    summaryOfInvestigation: string;
                    investigationReport: string;
                    confidenceLevel: number | unknown;
                    agentStatus: 'complete' | 'error' | 'abort' | 'timeout' | 'user_exit';
                    agentBranch: string;
                    operationOutcome: 'findings_recorded' | 'inconclusive' | 'agent_error' | 'cancelled';
                    rawResultJson: {
                        [key: string]: unknown;
                    };
                    createdAt?: string;
                    updatedAt?: string;
                } | {
                    executionId: unknown & unknown;
                    stepName: string;
                    proposed: Array<{
                        candidateTicketId: string;
                        score: number;
                    }>;
                    dismissed: Array<{
                        candidateTicketId: string;
                        score: number;
                    }>;
                    promoted: Array<{
                        candidateTicketId: string;
                        score: number;
                    }>;
                    createdAt?: string;
                    updatedAt?: string;
                } | {
                    executionId: unknown & unknown;
                    stepName: string;
                    agentStatus: 'complete' | 'error' | 'abort' | 'timeout' | 'user_exit';
                    agentBranch: string;
                    traceArtifactPath: string | unknown;
                    outcome: 'reproduced' | 'not_reproducible' | 'needs_user_feedback' | 'agent_error' | 'cancelled' | 'timeout';
                    summaryOfFindings: string;
                    confidenceLevel: number | unknown;
                    feedbackRequest: {
                        requestId: string;
                        reason: string;
                        questions: Array<string>;
                        assumptions: Array<string>;
                    } | unknown;
                    failureReason: string | unknown;
                    timeoutMs: number | unknown;
                    rawResultJson: {
                        [key: string]: unknown;
                    } | unknown;
                    createdAt?: string;
                    updatedAt?: string;
                } | {
                    executionId: unknown & unknown;
                    stepName: string;
                    githubAgentRunId: string | unknown;
                    githubMergeStatus: 'draft' | 'open' | 'closed' | 'merged';
                    devBranch: string | unknown;
                    baseBranch: string | unknown;
                    agentStatus: 'complete' | 'error' | 'abort' | 'timeout' | 'user_exit' | unknown;
                    agentBranch: string | unknown;
                    failingTestPaths: Array<string> | unknown;
                    failingTestCommitSha: string | unknown;
                    outcome: 'reproduced' | 'not_reproducible' | 'needs_user_feedback' | 'agent_error' | 'cancelled' | unknown;
                    summaryOfFindings: string | unknown;
                    confidenceLevel: number | unknown;
                    feedbackRequest: {
                        requestId: string;
                        reason: string;
                        questions: Array<string>;
                        assumptions: Array<string>;
                    } | unknown;
                    failureReason: string | unknown;
                    rawResultJson: {
                        [key: string]: unknown;
                    } | unknown;
                    createdAt?: string;
                    updatedAt?: string;
                } | {
                    executionId: unknown & unknown;
                    stepName: string;
                    githubAgentRunId: string | unknown;
                    githubMergeStatus: 'draft' | 'open' | 'closed' | 'merged';
                    devBranch: string | unknown;
                    baseBranch: string | unknown;
                    agentStatus: 'complete' | 'error' | 'abort' | 'timeout' | 'user_exit' | unknown;
                    agentBranch: string | unknown;
                    agentSummary: string | unknown;
                    fixedTestPath: string | unknown;
                    failingTestCommitSha?: string | unknown;
                    fixOperationOutcome: 'fixed' | 'not_fixed' | 'agent_error' | 'cancelled' | unknown;
                    summaryOfFix: string | unknown;
                    fixConfidenceLevel: number | unknown;
                    failureReason: string | unknown;
                    rawResultJson: {
                        [key: string]: unknown;
                    } | unknown;
                    createdAt?: string;
                    updatedAt?: string;
                } | unknown;
            };
        };
    };
};

export type PutApiWebhooksFailingTestFixStepOutputResponse = PutApiWebhooksFailingTestFixStepOutputResponses[keyof PutApiWebhooksFailingTestFixStepOutputResponses];
