import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { version } from "../../package.json";

export type StepSignalInfo = {
  key: string;
  sourcePath: string;
  type: string;
};

export type StepInfo = {
  key: string;
  name: string;
  version: number;
  signals: StepSignalInfo[];
};

type ScaffoldResult = {
  created: string[];
  skipped: string[];
};

function kebabToCamel(str: string): string {
  return str.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());
}

function buildPackageJson(): string {
  return JSON.stringify(
    {
      name: "pipeline-builder",
      private: true,
      type: "module",
      dependencies: {
        "@boboddy/sdk": `^${version}`,
        zod: "^4.4.2",
      },
    },
    null,
    2,
  );
}

const TSCONFIG_JSON = JSON.stringify(
  {
    compilerOptions: {
      target: "ES2022",
      lib: ["ES2022"],
      module: "ESNext",
      moduleResolution: "Bundler",
      moduleDetection: "force",
      verbatimModuleSyntax: true,
      resolveJsonModule: true,
      strict: true,
      isolatedModules: true,
      baseUrl: ".",
    },
    include: ["**/*.ts"],
    exclude: ["node_modules"],
  },
  null,
  2,
);

const GITIGNORE = `*
`;

const emptyCombinedPipelineTemplate = `// Auto-generated by \`boboddy pipelines pull\` — edit to define your pipelines
import { defineStep } from "@boboddy/sdk/definitions/steps";
import { definePipeline } from "@boboddy/sdk/definitions/pipelines";

export default definePipeline({
  key: "example-pipeline",
  name: "Example Pipeline",
  steps: [],
});
`;

function buildCombinedPipelineFile(steps: StepInfo[]): string {
  if (steps.length === 0) {
    return emptyCombinedPipelineTemplate;
  }

  const stepVarDefs = steps
    .map((step) => {
      const signalLines = step.signals
        .map(
          (s) =>
            `    { key: ${JSON.stringify(s.key)}, sourcePath: ${JSON.stringify(s.sourcePath)}, type: ${JSON.stringify(s.type)} },`,
        )
        .join("\n");
      const signalsSection =
        step.signals.length > 0
          ? `  signals: [\n${signalLines}\n  ],\n`
          : `  signals: [],\n`;
      return `const ${kebabToCamel(step.key)} = defineStep({
  key: ${JSON.stringify(step.key)},
  name: ${JSON.stringify(step.name)},
  version: ${String(step.version)},
${signalsSection}});`;
    })
    .join("\n\n");

  const [firstStep, ...remainingSteps] = steps;
  if (!firstStep) {
    return emptyCombinedPipelineTemplate;
  }

  const firstSignal = firstStep.signals[0];

  const firstStepEntry = firstSignal
    ? `    {
      step: ${kebabToCamel(firstStep.key)},
      advancement: {
        defaultOutcome: "block",
        rules: [Rule.when(${JSON.stringify(firstSignal.key)}, "greaterThanInclusive", 1, "continue")],
      },
    },`
    : `    { step: ${kebabToCamel(firstStep.key)} },`;

  const remainingStepEntries = remainingSteps
    .map((s) => `    { step: ${kebabToCamel(s.key)} },`)
    .join("\n");

  const stepEntries = remainingStepEntries
    ? `${firstStepEntry}\n${remainingStepEntries}`
    : firstStepEntry;

  const ruleImport = firstSignal ? `, Rule` : "";

  return `// Auto-generated by \`boboddy pipelines pull\` — edit to define your pipelines
import { defineStep } from "@boboddy/sdk/definitions/steps";
import { definePipeline${ruleImport} } from "@boboddy/sdk/definitions/pipelines";

${stepVarDefs}

export default definePipeline({
  key: "example-pipeline",
  name: "Example Pipeline",
  steps: [
${stepEntries}
  ],
});
`;
}

export function scaffoldPipelineBuilderDirectory(
  dir: string,
  steps: StepInfo[],
): ScaffoldResult {
  const result: ScaffoldResult = { created: [], skipped: [] };

  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }

  function writeFile(relPath: string, content: string): void {
    const filePath = join(dir, relPath);
    if (existsSync(filePath)) {
      result.skipped.push(relPath);
    } else {
      writeFileSync(filePath, content, "utf-8");
      result.created.push(relPath);
    }
  }

  writeFile("package.json", buildPackageJson());
  writeFile("tsconfig.json", TSCONFIG_JSON);
  writeFile(".gitignore", GITIGNORE);
  writeFile("pipeline.ts", buildCombinedPipelineFile(steps));

  return result;
}
